version: '3.8'

services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-false}
      - ENABLE_CUSTOM_CODES=${ENABLE_CUSTOM_CODES:-false}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-false}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge
